### ISSUE TITLE
Investigate FB API for getting users' friends

### ISSUE THREAD

**Issue by KlavierCat** [Coding-Drunk/bluebank#15]
See how this works.
Any chance to improve the UX on sending money to friends?

If it's complicated we can also accept user specifying receiver bank account 
or have some sorta sign up mechanism
or use Slack (support tagging while receiver not in dialog)

**Comment by mauriciodeoliveirareis** [comment]
There was some mention to OAuth in blue bank presentation, maybe we can take advantage of this OAuth to grab the user contacts.

**Comment by KlavierCat** [comment]
From the UX perspective this is "mocked up" for now. But from scientific, information perspective, esp. business model and stuff, this is definitely useful.
