### ISSUE TITLE
Survey Monkey for idea validation

### ISSUE THREAD

**Issue by KlavierCat** [Coding-Drunk/bluebank#21]
Questions:
1. Do you have a Facebook account?
2. Age group
3. How often do you use Facebook account?
4. Would you like to be able to send small amount of money to your Facebook friends via Facebook Messenger chat?
5. What would be the amount you'll be comfortable being able to send via Facebook? (need to rephrase this sentence a bit, but basically we put a cap so you can't send larger than this amount.)

**Comment by neko2016** [comment]
https://www.surveymonkey.com/r/GCSX5MM

**Comment by KlavierCat** [comment]
Survey Monkey done and sent.
